version: '3.8'

services:
    pgadmin4:
        image: dpage/pgadmin4:latest
        container_name: main_pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_PASSWORD: pgadmin@gmail.com
            PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
        ports:
            - '2000:80'
        networks:
            - pg-admin-network
networks:
    pg-admin-network:
        external:
            name: pg-admin-network
