version: '3.8'
services:
    db:
        image: postgres:latest
        container_name: node_postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./db:/docker-entrypoint-initdb.d/init.sql
        networks:
            - your-network # Ваша сеть
            - pg-admin-network

networks:
    your-network: # Ваша сеть
        driver: bridge
    pg-admin-network:
        driver: bridge
